# Server properties
server:
  port: 8080

# Database Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/als_skill_miner_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: kushan.microsoft16@gmail.com
    password: kushan@microsoft
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

app:
  location:
    uploaded-images: C:\Users\TR0J3N's PC\Pictures\Individual Project\uploaded-images\

